# Generated by Django 4.2.4 on 2023-11-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAnalisis', models.CharField(max_length=100, verbose_name='Analisis Disponibles')),
                ('descripcionAnalisis', models.CharField(max_length=300, verbose_name='Descripción del Analisis')),
            ],
        ),
        migrations.CreateModel(
            name='mediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremedicamento', models.CharField(max_length=25)),
                ('cantML', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='resultadopedidomedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MP', models.CharField(max_length=25, verbose_name='nombre pedido:')),
                ('DNI', models.CharField(max_length=25, verbose_name='descripcion pedido')),
                ('fecha', models.DateField(max_length=25)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoDocumento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('descripcionTipoDocumento', models.CharField(max_length=200, verbose_name='Descripción del Tipo de Documento')),
            ],
        ),
        migrations.CreateModel(
            name='usuarioRecepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=25)),
                ('documento', models.IntegerField()),
                ('direccion', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentosolicitado', models.CharField(max_length=25)),
                ('nombremedico', models.CharField(max_length=25)),
                ('fecha', models.DateField(max_length=25)),
                ('MP', models.CharField(max_length=25)),
                ('analisissolicitado', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app.analisisdisponibles')),
            ],
        ),
    ]
