# Generated by Django 4.2.7 on 2023-12-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAnalisis', models.CharField(max_length=100, verbose_name='Analisis Disponibles')),
                ('descripcionAnalisis', models.CharField(max_length=300, verbose_name='Descripción del Analisis')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('valor_ref_min', models.CharField(max_length=50, verbose_name='Valor Referencia Minimo')),
                ('valor_ref_max', models.CharField(max_length=50, verbose_name='Valor Referencia Maximo')),
            ],
        ),
        migrations.CreateModel(
            name='mediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremedicamento', models.CharField(max_length=25)),
                ('cantML', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremedico', models.CharField(max_length=25)),
                ('especialidad', models.CharField(max_length=25)),
                ('MP', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('descripcion', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo Documento')),
                ('documento', models.CharField(max_length=50, verbose_name='Numero Documento')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='resultadopedidomedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MP', models.CharField(max_length=25, verbose_name='nombre pedido:')),
                ('DNI', models.CharField(max_length=25, verbose_name='descripcion pedido')),
                ('fecha', models.DateField(max_length=26)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=10)),
                ('estudios', models.ManyToManyField(blank=True, to='app.estudio')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hallado', models.CharField(max_length=50, verbose_name='Valor Hallado')),
                ('estudio', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app.estudio')),
                ('solicitud', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentosolicitado', models.CharField(max_length=25)),
                ('nombremedico', models.CharField(max_length=25)),
                ('fecha', models.DateField(max_length=25)),
                ('MP', models.CharField(max_length=25)),
                ('analisissolicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.analisisdisponibles')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('is_recep', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
