# Generated by Django 4.2.4 on 2023-11-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipodocumento',
        ),
        migrations.DeleteModel(
            name='TipoDocumento',
        ),
    ]
