# Generated by Django 4.2.7 on 2023-12-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estudio_valor_hallado_delete_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estudios',
            field=models.ManyToManyField(blank=True, related_name='estudios', to='app.estudio'),
        ),
    ]
