# Generated by Django 4.2.7 on 2023-12-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_solicitud_estudios'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='unidad_medida',
            field=models.CharField(max_length=10, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
