# Generated by Django 4.2.4 on 2023-11-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoDocumento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('descripcionTipoDocumento', models.CharField(max_length=200, verbose_name='Descripción del Tipo de Documento')),
            ],
        ),
    ]
