# Generated by Django 4.2.4 on 2023-11-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipodocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipodocumento'),
            preserve_default=False,
        ),
    ]
