# Generated by Django 4.2.4 on 2023-11-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_usuario_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAnalisis', models.CharField(max_length=100, verbose_name='Analisis Disponibles')),
                ('descripcionAnalisis', models.CharField(max_length=200, verbose_name='Descripción del Analisis')),
            ],
        ),
        migrations.AlterField(
            model_name='receta',
            name='analisissolicitado',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app.analisisdisponibles'),
        ),
    ]
