classDiagram
  
    class Laboratorio {
    +int numeroSolicitud
    +string fechaSolicitud
    +string estado
    +string fechaFinalizacion
    +registrarSolicitud()
    +actualizarEstado()
    +generarInforme()
  }

  class Recepcionista {
    +string nombre
    +string apellido

    +solicitarReceta()
    +registrarSolicitud()
    +ingresarAlSAC()
    +RevisarReceta()
    +SolicitarDNIPaciente()
    +ingresarDNIalSAC()
    +EscanearRecetaPDF()
    +ConfirmarSolicitud()
    +InformarAlPacienteQueVayaSalaDeEspera()

  }

  class Paciente {
    +string nombre
    +string apellido
    +string documento
    +string direccion
    +string telefono
    +string email

    +DarDNIalRecepcionista()
    +IngresarSusDatosSiVienePorPrimeraVez()
  }

  class Medico {
    +string nombre
    +string apellido
    +string matricula
    
    +solicitarAnalisis()
    +validarMatricula()
  }

  class Extraccionista {
    +string nombre
    +string apellido
    +RecibirSolicitud()
    +registrarMuestras()

  }

  class ResponsableAnalisis {
    +str nombre
    +str descripcion

    +registrarResultado()
  }

  class Estudio {
    +string codigo
    +string nombre
    +string metodo
    +string unidadMedida
    +string rangoReferencia


  }

  class SAC {
    +str nombre
    +str descripcion

    +validarMatriculaMedico()
    +conectarconWebServiceColegioMedico()
    +enviarEmail()
    +generarReporte()
    +MostrarDatosPaciente()
    +InformarQueNoEstaRegistrado()
    +HabiltarBotonRegistro()
    +GenerarListaEstudios()
    +RegistrarSolicitud()
    +ActualizarPantallasConDatosPaciente()
    +asignarSolicitud()
    +ActualizarSolicitudYinformarEnPantalla()
  }

  Laboratorio  --> "1..*" Recepcionista : tiene
  Laboratorio  --> "1..*" Paciente : tiene
  Laboratorio  --> "1..*" Medico : tiene
  Laboratorio --> "1..*" Extraccionista : tiene
  Laboratorio  --> "1" ResponsableAnalisis : tiene
  Laboratorio "1..*" -- "1..*" Estudio : incluye
  Laboratorio  --> "1" SAC : utiliza

  Medico --|> Paciente : atiende
  Extraccionista --|> Laboratorio : atiende
  ResponsableAnalisis --|> Laboratorio : gestiona

  Recepcionista --|> SAC : utiliza
  Medico --|> SAC : utiliza
  Paciente --|> SAC : utiliza
  Extraccionista --|> SAC : utiliza
  ResponsableAnalisis --|> SAC : utiliza

